apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: skywalker-application-openldap
  namespace: cluster

spec:
  destination:
    namespace: application
    name: in-cluster
  project: skywalker
  source:
    chart: app-template
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 0.2.*
    helm:
      releaseName: openldap
      valuesObject:
        image:
          repository: bitnami/openldap
          tag: 2.6.4
        env:
          TZ: America/New_York
          LDAP_ROOT: dc=feldman,dc=tech
        service:
          main:
            ports:
              http:
                enabled: false
              ldap:
                enabled: true
                primary: true
                protocol: TCP
                port: 1389
              ldaps:
                enabled: true
                protocol: TCP
                port: 1636
        persistence:
          data:
            enabled: true
            mountPath: /bitnami/openldap
            accessMode: ReadWriteOnce
            size: 4Gi
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        podSecurityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0
