apiVersion: v1
kind: LimitRange

metadata:
  name: home-limit-range

spec:
  limits:
  - type: Container
    default:
      memory: 256Mi
      cpu: 500m
    defaultRequest:
      memory: 128Mi
      cpu: 256m
