apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: home

resources:
  - home.namespace.yaml
  - home.limitrange.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    releaseName: esphome
    version: 3.1.0
    valuesFile: esphome.values.yaml
