apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: home

resources:
  - home.namespace.yaml
  - home.limitrange.yaml

  - authentik
  - home-assistant
  - grafana
  - homepage
  - mealie
  - node-red
  - snipe-it
  - spoolman
  - tc-snipe
