apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tc-snipe

resources:
  - snipeit.virtualservice.yaml
  - snipeit.sealed-secret.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    releaseName: tc-snipe
    version: 1.5.1
    valuesFile: ./values.yaml
