apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cert-manager

resources:
  - cloudflare-api-token.sealed-secret.yaml
  - cluster-issuers.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cluster
    version: v1.16.3
    valuesInline:
      installCRDs: true