apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: deluge

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: deluge
    version: 3.2.1
    valuesFile: deluge.values.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
