apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: radarr

resources:
  - radarr.virtualservice.yaml

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: radarr
    version: 1.5.1
    valuesFile: radarr.values.yaml