apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: longhorn-system

resources:
  - longhorn-system.namespace.yaml

  # - default-backup.recurringjob.yaml
  - longhorn-single-replica-ephemeral.storageclass.yaml
  - longhorn.virtualservice.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    version: 1.10.1
    namespace: longhorn-system
    valuesFile: values.yaml
