apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: jellyseerr

resources:
  - jellyseerr.virtualservice.yaml

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: jellyseerr
    version: 1.5.1
    valuesFile: jellyseerr.values.yaml
