apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: application

resources:
  - application.namespace.yaml

  - authentik
  - freshrss
  - grafana
  - grocy
  - home-assistant
  - homepage
  - mealie
  - node-red
  - snipe-it
  - spoolman
