apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: application

resources:
  - application.namespace.yaml

  - authentik
  - freshrss
  - grafana
  - home-assistant
  - homepage
  - mealie
  - node-red
  - snipe-it
  - spoolman

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: grafana
    version: 2.2.0
    valuesFile: values/grafana.yaml