apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kube-system

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    releaseName: sealed-secrets-controller
    version: 2.17.1
    namespace: kube-system
    includeCRDs: true
