apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: snipe-it

resources:
  - snipeit.virtualservice.yaml
  - snipeit.sealed-secret.yaml

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: spoolman
    version: 1.5.1
    valuesFile: ../values/snipeit.yaml