apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sonarr

resources:
  - sonarr.virtualservice.yaml

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: sonarr
    version: 1.5.1
    valuesFile: sonarr.values.yaml