image:
  repository: jellyfin/jellyfin
  tag: 10.9.7
env:
  TZ: America/New_York
service:
  main:
    ports:
      http:
        port: 8096
persistence:
  config-new:
    enabled: true
    type: custom
    volumeSpec:
      iscsi:
        targetPortal: 10.10.90.30:3260
        iqn: iqn.2005-10.org.freenas.ctl:skywalker-jellyfin-config
        lun: 0
        fsType: ext4
  config:
    enabled: true
    size: 6Gi
  media:
    enabled: true
    type: nfs
    server: truenas.feldman.in
    path: /mnt/primary/Media
    mountPath: /media
