
kind: StorageClass
apiVersion: storage.k8s.io/v1

metadata:
  name: longhorn-single-replica-ephemeral
  namespace: cluster

provisioner: driver.longhorn.io
allowVolumeExpansion: true

parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fsType: "ext4"
  dataLocality: "best-effort"
  reclaimPolicy: "Delete"
