apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: printers

resources:
  - printers.namespace.yaml
  
  - openspoolman-env.sealed-secret.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    releaseName: openspoolman
    version: 3.1.0
    valuesFile: ./openspoolman.values.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
