controllers:
  openspoolman:
    containers:
      app:
        image:
          repository: ghcr.io/drndos/openspoolman
          tag: latest
        env:
          TZ: America/New_York
        envFrom:
          - secretRef:
              name: openspoolman-env

service:
  app:
    controller: openspoolman
    ports:
      http:
        port: 8000

route:
  app:
    enabled: true
    parentRefs:
      - name: feldman-in
        namespace: istio-system
    hostnames: ["openspoolman.feldman.in"]
    rules:
      - backendRefs:
          - name: openspoolman
            port: 8000
            namespace: printers
