apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: awx

metadata:
  name: application

resources:
  - awx.namespace.yaml

  - awx.awx.yaml
  - awx.httproute.yaml
  - awx.postgres.yaml

helmCharts:
  - name: awx-operator
    repo: https://ansible-community.github.io/awx-operator-helm/
    releaseName: awx-operator
    version: 2.19.1
    namespace: awx
    includeCRDs: true
