apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: skywalker-monitoring-grafana-loki
  namespace: cluster

spec:
  destination:
    namespace: monitoring
    name: in-cluster
  project: skywalker
  source:
    chart: grafana-loki
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.2.0
    helm:
      releaseName: grafana-loki
      valuesObject:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        compactor:
          persistence:
            enabled: false
        ingestor:
          persistence:
            enabled: false
        querier:
          persistence:
            enabled: false
        ruler:
          persistence:
            enabled: false