apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: democratic-csi-freenas-isci

namespace: democratic-csi

resources:
  - democratic-csi-freenas-isci-driver-config.sealed-secret.yaml

helmCharts:
  - name: democratic-csi
    repo: https://democratic-csi.github.io/charts/
    releaseName: democratic-csi-freenas-isci
    version: '0.14.5'
    namespace: democratic-csi
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - path: "cr.patch.yaml"
    target:
      kind: ClusterRole
