controllers:
  grocy:
    containers:
      app:
        image:
          repository: lscr.io/linuxserver/grocy
          tag: 4.2.0
        env:
          TZ: America/New_York

persistence:
  config:
    enabled: true
    type: custom
    volumeSpec:
      iscsi:
        targetPortal: 10.10.90.30:3260
        iqn: iqn.2005-10.org.freenas.ctl:skywalker-grocy-config
        lun: 0
        fsType: ext4

service:
  app:
    controller: grocy
    ports:
      http:
        port: 80

route:
  app:
    enabled: true
    parentRefs:
      - name: feldman-in
        namespace: istio-system
    hostnames: ["grocy.feldman.in"]
    rules:
      - backendRefs:
          - name: grocy
            port: 80
            namespace: application
