apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grocy

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: grocy
    version: 3.1.0
    valuesFile: grocy.values.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
