apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mealie

resources:
  - mealie.virtualservice.yaml
  - mealie-env.sealed-secret.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    releaseName: mealie
    version: 1.5.1
    valuesFile: values.yaml