apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: node-red

resources:
  - node-red.virtualservice.yaml

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: node-red
    version: 3.6.1
    valuesFile: ../values/node-red.yaml