apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: home-assistant

resources:
  - home-assistant.virtualservice.yaml

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: home-assistant
    version: 3.1.0
    valuesFile: home-assistant.values.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
