---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-env
  namespace: application
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgCFNdJ/xIwW9VdAGg1lv7cPBY57Y93XCuqvNvSsw1moQEZbE+1Vys9qKYU7Ib5/pUypyCAuudhxzCNldqlaIJo2GMASv/ff6OjzKqbKLn5+uxxgGcal3+riKWEe+odi/FWqaejhh7isvIjXM6HovYitvCRoprj/Bo+QjyT8ayTybZ6VsmkQNh6HpwjbfsAbHWMGsVKzHkdGTwCGlMVZ29ojoTQzbW5X6+QBZt+dHKBtPIRUE78vxXlvnDAXSiTqLk0F90JdrP6hYgXo5nA8tlQG8R36JEtAdrU/Kys4kkHLTrLhjb1BZ/RNkgsOOsORV/CRHkdlaND+7WH10W2rBHxb3OjxGKOS0cQvb1k/79KpiAroCYRjUICgIRE3PuUG/xPh/Qr81yuIC5TvLRWxHGjBmO/yd/h5z9vilVde2N9+GaCLkiGSVUXzXsibpWSm8PvKXZIw40AqC5YntoRFp4SCqOCkyrd6dDPOrfAbBc+JLsFgiymKIX/Sh1IZskPEq2ypfSZVPP97MAD7Bp5qRmqR1YkiyKkjbtdnA260iYH6Ijwslbx0mKfwLHPV4+nZ2cGCaBdJi48nepRDeXfxIhU9slPzUmCPADmm9J2ES6UcODGd9roToNGA2ddWcaC3QmXXb1rnGcorXfTY2l+5SyTT0XMTh4wUmAJZqjpGYOJV+aQu9wkDbGK1+OMoa7gV5C/5C/Whgp9PwhcSgKFiBymHUNtAjd2lg7OBsrzaaQAAs+vBLIKWiWeq2qqXUekJXvLynA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-env
      namespace: application
    type: Opaque
