apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: spoolman

resources:
  - spoolman.postgres.yaml


helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    releaseName: spoolman
    version: 3.1.0
    valuesFile: ../values/spoolman.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
