apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-clone
spec:
  storageClassName: freenas-api-iscsi
  dataSource:
    name: freshrss-data
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi