apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: freshrss

resources:
  - freshrss.virtualservice.yaml
  - freshrss-env.sealed-secret.yaml

  - clone.yaml

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: freshrss
    version: 1.5.1
    valuesFile: values.yaml
