apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: printer-v02-8nhft
spec:
  hosts:
    - printer-v02-8nhft.local
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: printer-v02-8nhft
spec:
  parentRefs:
  - kind: ServiceEntry
    group: networking.istio.io
    name: printer-v02-8nhft
  rules:
  - backendRefs:
    - kind: Hostname
      group: networking.istio.io
      name: printer-v02-8nhft.local
      port: 80
