apiVersion: v1
kind: LimitRange

metadata:
  name: cluster-limit-range

spec:
  limits:
  - type: Container
    default:
      memory: 2Gi
      cpu: 3000m
    defaultRequest:
      memory: 256Mi
      cpu: 500m
