controllers:
  fluidd:
    containers:
      app:
        image:
          repository: ghcr.io/fluidd-core/fluidd
          tag: v1.30.0
        env:
          TZ: America/New_York

service:
  app:
    controller: fluidd
    ports:
      http:
        port: 80

route:
  app:
    enabled: true
    parentRefs:
      - name: feldman-in
        namespace: istio-system
    hostnames: ["fluidd.feldman.in"]
    rules:
      - backendRefs:
          - name: fluidd
            port: 80
            namespace: printers

persistence:
  config:
    enabled: true
    type: configMap
    name: fluidd-config
    globalMounts:
      - path: /usr/share/nginx/html/config.json
        subPath: config.json
        readOnly: true
