apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fluidd

resources:
  - fluidd-config.configmap.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    releaseName: fluidd
    version: 3.1.0
    valuesFile: ../values/fluidd.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
