apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fluidd


helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: fluidd
    version: 3.1.0
    valuesFile: ../values/fluidd.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
