apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: fluidd

resources:
  - fluidd-config.configmap.yaml

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: fluidd
    version: 3.6.1
    valuesFile: ../values/fluidd.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1beta1/HTTPRoute
