apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: media

resources:
  - media.namespace.yaml

  - deluge
  - jellyfin
  - jellyseer
  - prowlarr
  - radarr
  - requestrr
  - sonarr
  - tdarr

helmCharts:
  - name: app-template
    repo: http://bjw-s.github.io/helm-charts/
    releaseName: jellyfin
    version: 1.5.1
    valuesFile: values/jellyfin.yaml
